### ISSUE TITLE
How to setup on Vanilla Manjaro Openbox Edition ?

### ISSUE THREAD

**Issue by aswinmohanme** [s0la/orw#5]
The results looks absolutely gorgeous. But I ran into some trouble while installing this on a vanilla Manjaro OpenBox Edition.

* pip3 was not present in the installation
* Could not install cava
* The installation is broken on start

Also is there any way to toggle a verbose mode, so we can see the entire output of the installation script ?

**Comment by s0la** [comment]
Hey,
Thanks for giving this project a shot, and for taking the time to report those issuse! :)

I will install Manjaro on usb so I can boot it live, and I'll get back to you with the results :)
As for verbose mode, I'll add a flag so one can enable full output, thanks for pointing that out! :)

**Comment by aswinmohanme** [comment]
Tried the same script on arcolinux and that works nicely.

**Comment by s0la** [comment]
Ok, that's good to know.. In fact, I only tested it on Archbang and vanila Arch, so it's definitely Manjaro specific issues..
No worries though, I'm downloading Manjaro as we speak, so hopefully I'll know what causes the problems soon :)
